### ISSUE TITLE
Make the number of "winners" configurable

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/hexboard#14]
WINNER_COUNT = INT(default=10)

**Comment by bleathem** [comment]
Making the number of winners arbitrary will require improving the code that zooms the winners and places them above the hexboard.  The math that calculates the positions currently assumes a winner count of 10.

**Comment by ryanj** [comment]
The UI could still use some help, but the basic implementation is done.  Set `WINNER_COUNT` to any integer value in the range 1:10 

See #17
