### ISSUE TITLE
hexboard doesn't works properly in OSE 3.1

### ISSUE THREAD

**Issue by hodrigohamalho** [2015-Middleware-Keynote/hexboard#24]
![screen shot 2015-11-23 at 1 51 22 am](https://cloud.githubusercontent.com/assets/252998/12178380/4c9f0f1a-b558-11e5-91bd-6e070483f6e6.png)

I replaced API references, but it isn't sufficient to get it working.
https://github.com/hodrigohamalho/hexboard/commit/74607f0a22672f540aa665980cff4459daeaa680

**Comment by ryanj** [comment]
Hi @hodrigohamalho,
What setup methods are you using for OpenShift, and for this application?

Do you get the same error when launching the application using this method?:

    oc new-app https://raw.githubusercontent.com/2015-Middleware-Keynote/hexboard/master/app_template.json -p ACCESS_TOKEN=$(oc whoami -t)

**Comment by hodrigohamalho** [comment]
It's working now, thanks @ryanj
