### ISSUE TITLE
Missing resources on direct access

### ISSUE THREAD

**Issue by hodrigohamalho** [2015-Middleware-Keynote/hexboard#29]
![screen shot 2016-01-08 at 3 04 34 pm](https://cloud.githubusercontent.com/assets/252998/12204078/37b245f6-b619-11e5-9d60-93b99e371550.png)

**Comment by ryanj** [comment]
Thanks for reporting.  

I'm able to reproduce this issue, but it's not a critical error. The demo should still work fine without the extra web fonts. 

sketch.png should be available after a sketch is submitted.

**Comment by hodrigohamalho** [comment]
@ryanj ok, thank you.

**Comment by ryanj** [comment]
This should be fixed now. Please re-open if you're still seeing the issue.
