### ISSUE TITLE
pod watch re-connect loop

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/hexboard#32]
logs are being flooded with reconnects (674776 in ~12 hours):

```
POD Thu Jan 14 2016 15:24:15 GMT-0500 (EST)
POD Connection error: { type: 'end', msg: 'Request terminated.' }
POD Attmepting a re-connect (#674776)
POD list options https://172.30.0.1/api/v1/namespaces/demo/pods
POD watch options https://172.30.0.1/api/v1/namespaces/demo/pods watch=true
POD Connection success to watch endpoint
```

Here is the section that is blowing up:
https://github.com/2015-Middleware-Keynote/hexboard/blob/master/server/hexboard/pod.js#L250-L256

**Comment by detiber** [comment]
@ryanj I believe this is expected since the watches timeout and must be re-initiated when they do.

**Comment by ryanj** [comment]
Thanks for the patch @detiber!
