### ISSUE TITLE
Error building Sketchpod in OSE 3.1

### ISSUE THREAD

**Issue by tgaillard1** [2015-Middleware-Keynote/hexboard#34]
In attempting to run the Keynote application I am not getting the error below which looks related to a node.js versioning of a module (although I'm not sure).  I used to run this same project on the same VM image (it is actually the demobuilder image used by many people at Red Hat) but I never encountered this error before so I believe something has changed upstream.  Please let me know if you need more information.  Thanks

E0218 11:40:35.843580       1 util.go:85] npm ERR! notarget No compatible version found: qs@'>=6.0.2-0 <6.1.0-0'
E0218 11:40:35.843584       1 util.go:85] npm ERR! notarget Valid install targets:
E0218 11:40:35.843590       1 util.go:85] npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","1.0.0","1.0.1","1.0.2","1.1.0","1.2.0","1.2.1","1.2.2","2.0.0","2.1.0","2.2.0","2.2.1","2.2.2","2.2.3","2.2.4","2.2.5","2.3.0","2.3.1","2.3.2","2.3.3","2.4.0","2.4.1","2.4.2","3.0.0","3.1.0","4.0.0","5.0.0","5.1.0","5.2.0","6.0.0","6.0.1"]
E0218 11:40:35.843596       1 util.go:85] npm ERR! notarget 
E0218 11:40:35.843602       1 util.go:85] npm ERR! notarget This is most likely not a problem with npm itself.
E0218 11:40:35.843608       1 util.go:85] npm ERR! notarget In most cases you or one of your dependencies are requesting
E0218 11:40:35.843612       1 util.go:85] npm ERR! notarget a package version that doesn't exist.
E0218 11:40:35.843618       1 util.go:85] 
E0218 11:40:35.843699       1 util.go:85] npm ERR! System Linux 3.10.0-327.el7.x86_64
E0218 11:40:35.843814       1 util.go:85] npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
E0218 11:40:35.843836       1 util.go:85] npm ERR! cwd /opt/app-root/src
E0218 11:40:35.843855       1 util.go:85] npm ERR! node -v v0.10.40
E0218 11:40:35.843862       1 util.go:85] npm ERR! npm -v 1.4.28
E0218 11:40:35.843926       1 util.go:85] npm ERR! code ETARGET

**Comment by ryanj** [comment]
@tgaillard1 please try rebuilding. Let me know if you get the same error.

**Comment by tgaillard1** [comment]
Ryan,
It works now.  Great work.  Thanks for the effort.  I’m going to get the latest GA version of OSE and run through all the tests again.  I’ll post any findings.  

Thanks,
Tim

> On Feb 23, 2016, at 2:51 PM, ryan jarvinen <notifications@github.com> wrote:
> 
> @tgaillard1 <https://github.com/tgaillard1> please try rebuilding. Let me know if you get the same error.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/2015-Middleware-Keynote/hexboard/issues/34#issuecomment-187929984>.
> 


Tim Gaillard
Red Hat Solutions Architect
Phoenix, Arizona
480-717-7767  Cell
