### ISSUE TITLE
npm ERR! SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by tgaillard1** [2015-Middleware-Keynote/hexboard#37]
During the build process for the hexboard pod I keep getting the npm ERR! SELF_SIGNED_CERT_IN_CHAIN in the build logs.  Last 500 lines attached with this issue.

I'm using a OSE build v3.1.1.6 with kubernetes v1.1.0-origin-1107.  To help validate it wasn't my environment I used branch v3.1.0 and it completed the build process without any errors.  That branch has some legacy issues so I'd really like to use the current master if possible.  Please let me know if you need more information.  Thanks -- Tim

I0517 19:19:45.027739       1 sti.go:173] The value of ALLOWED_UIDS is [1-]
I0517 19:19:45.035630       1 docker.go:224] Image 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest available locally
I0517 19:19:45.051801       1 sti.go:195] Creating a new S2I builder with build config: "Builder Name:\t\tNode.js 0.10\nBuilder Image:\t\t172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest\nSource:\t\t\tfile:///tmp/s2i-build521427221/upload/src#master\nOutput Image Tag:\t172.30.132.21:5000/testx/hexboard:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=hexboard-1,OPENSHIFT_BUILD_NAMESPACE=testx,OPENSHIFT_BUILD_SOURCE=http://github.com/ryanj/hexboard,OPENSHIFT_BUILD_REFERENCE=master\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nBuilder Pull Policy:\tif-not-present\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build521427221\nDocker NetworkMode:\tcontainer:955f9294758a29e0fdbd9b45dba324229a6887048bd072e30af7d7ec4fd2bc47\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0517 19:19:45.057227       1 docker.go:224] Image 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest available locally
I0517 19:19:45.076737       1 sti.go:140] Preparing to build 172.30.132.21:5000/testx/hexboard:latest
I0517 19:19:51.965182       1 source.go:189] Cloning source from http://github.com/ryanj/hexboard
I0517 19:20:22.816765       1 docker.go:224] Image 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest available locally
I0517 19:20:22.816805       1 docker.go:344] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0517 19:20:22.816834       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/assemble
I0517 19:20:22.816841       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/run
I0517 19:20:22.821190       1 docker.go:224] Image 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest available locally
I0517 19:20:22.821281       1 docker.go:344] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0517 19:20:22.821336       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/save-artifacts
I0517 19:20:22.821485       1 sti.go:221] Using assemble from upload/src/.sti/bin
I0517 19:20:22.821504       1 sti.go:221] Using run from image:///usr/libexec/s2i
I0517 19:20:22.821511       1 sti.go:221] Using save-artifacts from upload/src/.sti/bin
I0517 19:20:22.821515       1 sti.go:148] Clean build will be performed
I0517 19:20:22.821541       1 sti.go:151] Performing source build from file:///tmp/s2i-build521427221/upload/src#master
I0517 19:20:22.821549       1 sti.go:164] Running "assemble" in "172.30.132.21:5000/testx/hexboard:latest"
I0517 19:20:22.821563       1 sti.go:412] Using image name 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest
I0517 19:20:22.821582       1 sti.go:416] No .sti/environment provided (no environment file found in application sources)
I0517 19:20:22.824892       1 docker.go:390] Both scripts and untarred source will be placed in '/tmp'
I0517 19:20:22.824911       1 docker.go:529] Creating container using config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[OPENSHIFT_BUILD_NAME=hexboard-1 OPENSHIFT_BUILD_NAMESPACE=testx OPENSHIFT_BUILD_SOURCE=http://github.com/ryanj/hexboard OPENSHIFT_BUILD_REFERENCE=master] Cmd:[/bin/sh -c tar -C /tmp -xf - && /tmp/scripts/assemble] DNS:[] Image:172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest Volumes:map[] VolumeDriver: VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[]}
I0517 19:20:29.892908       1 docker.go:543] Attaching to container
I0517 19:20:29.895213       1 docker.go:549] Starting container
I0517 19:20:32.350584       1 docker.go:479] Waiting for container
---> Restoring npm_modules
---> Installing application source
---> Building your Node application from source
E0517 19:20:57.642516       1 util.go:91] npm info it worked if it ends with ok
E0517 19:20:57.646162       1 util.go:91] npm info using npm@2.14.13
E0517 19:20:57.646179       1 util.go:91] npm info using node@v0.10.40
E0517 19:21:02.003409       1 util.go:91] npm WARN package.json hexboard@0.0.1 license should be a valid SPDX license expression
E0517 19:21:02.008814       1 util.go:91] npm info shrinkwrap file "/opt/app-root/src/npm-shrinkwrap.json"
E0517 19:21:02.053843       1 util.go:91] npm info preinstall hexboard@0.0.1
E0517 19:21:02.083783       1 util.go:91] npm info package.json gulp-plumber@0.6.6 No license field.
E0517 19:21:02.083818       1 util.go:91] npm info package.json gulp-rename@1.2.2 No license field.
E0517 19:21:02.083830       1 util.go:91] npm info package.json jquery@2.1.4 No license field.
E0517 19:21:02.083837       1 util.go:91] npm info package.json node-env-file@0.1.7 No license field.
E0517 19:21:02.083842       1 util.go:91] npm info package.json node-inspector@0.9.2 No license field.
E0517 19:21:02.083846       1 util.go:91] npm info package.json numeral@1.5.3 No license field.
E0517 19:21:02.083855       1 util.go:91] npm info package.json patternfly@1.3.0 No repository field.
E0517 19:21:02.083862       1 util.go:91] npm info package.json q@1.4.1 license should be a valid SPDX license expression
E0517 19:21:02.083869       1 util.go:91] npm info package.json rx-dom@6.0.0 No license field.
E0517 19:21:02.083873       1 util.go:91] npm info package.json rx-node@1.0.0 No license field.
E0517 19:21:02.150807       1 util.go:91] npm info package.json stream-filter@1.0.0 license should be a valid SPDX license expression
E0517 19:21:02.150836       1 util.go:91] npm info package.json uuid-js@0.7.5 No license field.
E0517 19:21:02.150845       1 util.go:91] npm info shrinkwrap file "/opt/app-root/src/npm-shrinkwrap.json"
E0517 19:21:04.015044       1 util.go:91] npm info attempt registry request try #1 at 19:21:02
E0517 19:21:04.016046       1 util.go:91] npm http request GET https://registry.npmjs.org/gulp-template
E0517 19:21:04.027764       1 util.go:91] npm info retry fetch attempt 1 at 19:21:04
E0517 19:21:04.030386       1 util.go:91] npm info attempt registry request try #1 at 19:21:04
E0517 19:21:04.032578       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:21:04.124236       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:21:04.151276       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:21:14.128754       1 util.go:91] npm info attempt registry request try #2 at 19:21:14
E0517 19:21:14.128798       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:21:14.153604       1 util.go:91] npm info attempt registry request try #2 at 19:21:14
E0517 19:21:14.153675       1 util.go:91] npm http request GET https://registry.npmjs.org/gulp-template
E0517 19:21:14.185350       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:21:14.203161       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:22:14.248870       1 util.go:91] npm info attempt registry request try #3 at 19:22:14
E0517 19:22:14.248898       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:22:14.248903       1 util.go:91] npm info attempt registry request try #3 at 19:22:14
E0517 19:22:14.248907       1 util.go:91] npm http request GET https://registry.npmjs.org/gulp-template
E0517 19:22:14.295191       1 util.go:91] npm ERR! fetch failed https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:22:14.295215       1 util.go:91] npm WARN retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:22:24.294310       1 util.go:91] npm info retry fetch attempt 2 at 19:22:24
E0517 19:22:24.294501       1 util.go:91] npm info attempt registry request try #1 at 19:22:24
E0517 19:22:24.296621       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:22:24.327601       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:22:34.339014       1 util.go:91] npm info attempt registry request try #2 at 19:22:34
E0517 19:22:34.339050       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:22:34.369238       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:23:34.423798       1 util.go:91] npm info attempt registry request try #3 at 19:23:34
E0517 19:23:34.423867       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:23:34.469143       1 util.go:91] npm ERR! fetch failed https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:23:34.469277       1 util.go:91] npm WARN retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:24:34.515251       1 util.go:91] npm info retry fetch attempt 3 at 19:24:34
E0517 19:24:34.515452       1 util.go:91] npm info attempt registry request try #1 at 19:24:34
E0517 19:24:34.516476       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:24:34.545368       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:24:44.562401       1 util.go:91] npm info attempt registry request try #2 at 19:24:44
E0517 19:24:44.562436       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:24:44.591109       1 util.go:91] npm info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
E0517 19:25:44.646234       1 util.go:91] npm info attempt registry request try #3 at 19:25:44
E0517 19:25:44.646287       1 util.go:91] npm http fetch GET https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:25:44.679844       1 util.go:91] npm ERR! fetch failed https://registry.npmjs.org/gulp-rename/-/gulp-rename-1.2.2.tgz
E0517 19:25:44.679896       1 util.go:91] npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
E0517 19:25:44.679901       1 util.go:91] npm ERR! argv "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
E0517 19:25:44.679906       1 util.go:91] npm ERR! node v0.10.40
E0517 19:25:44.679909       1 util.go:91] npm ERR! npm  v2.14.13
E0517 19:25:44.679913       1 util.go:91]
E0517 19:25:44.679917       1 util.go:91] npm ERR! SELF_SIGNED_CERT_IN_CHAIN
E0517 19:25:44.679920       1 util.go:91] npm ERR!
E0517 19:25:44.679924       1 util.go:91] npm ERR! If you need help, you may report this error at:
E0517 19:25:44.679927       1 util.go:91] npm ERR!     <https://github.com/npm/npm/issues>
E0517 19:25:44.710011       1 util.go:91]
E0517 19:25:44.710097       1 util.go:91] npm ERR! Please include the following file with any support request:
E0517 19:25:44.710106       1 util.go:91] npm ERR!     /opt/app-root/src/npm-debug.log
I0517 19:25:44.933324       1 docker.go:481] Container wait returns with 1 and <nil>
I0517 19:25:44.933380       1 docker.go:488] Container exited
I0517 19:25:48.812389       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build521427221
I0517 19:25:48.812453       1 fs.go:117] Removing directory '/tmp/s2i-build521427221'
F0517 19:25:49.244831       1 builder.go:185] Error: build error: non-zero (13) exit code from 172.30.157.58:5000/openshift3/nodejs-010-rhel7:latest

**Comment by ryanj** [comment]
Do you get similar errors with the CentOS base image?

I usually use this base to avoid running my new JS code on a historic releases of nodejs and npm: https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/

**Comment by tgaillard1** [comment]
Sorry I haven’t run it on CentOS

> On May 27, 2016, at 9:55 AM, ryan jarvinen <notifications@github.com> wrote:
> 
> Do you get similar errors with the CentOS base image?
> 
> I usually use this base to avoid running my new JS code on a historic releases of nodejs and npm: https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/ <https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/2015-Middleware-Keynote/hexboard/issues/37#issuecomment-222198337>, or mute the thread <https://github.com/notifications/unsubscribe/APPuJR_80UbF7IPZj3V5COJS14l9TV1bks5qFyIfgaJpZM4Igzs0>.
> 


Tim Gaillard
Red Hat Solutions Architect
Phoenix, Arizona
480-717-7767  Cell

**Comment by tgaillard1** [comment]
Hi Ryan,
So how can I get my instance of OSE to use these for the base nodejs and npm images?  Sorry I’m not sure of the best practice to update my OSE to have it use these. 

Thanks in advance,
Tim


> On May 27, 2016, at 9:56 AM, Tim Gaillard <tgaillar@redhat.com> wrote:
> 
> Sorry I haven’t run it on CentOS
>> On May 27, 2016, at 9:55 AM, ryan jarvinen <notifications@github.com> wrote:
>> 
>> Do you get similar errors with the CentOS base image?
>> 
>> I usually use this base to avoid running my new JS code on a historic releases of nodejs and npm: https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/ <https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub <https://github.com/2015-Middleware-Keynote/hexboard/issues/37#issuecomment-222198337>, or mute the thread <https://github.com/notifications/unsubscribe/APPuJR_80UbF7IPZj3V5COJS14l9TV1bks5qFyIfgaJpZM4Igzs0>.
>> 
> 
> 
> Tim Gaillard
> Red Hat Solutions Architect
> Phoenix, Arizona
> 480-717-7767  Cell
> 
> 
> 
> 


Tim Gaillard
Red Hat Solutions Architect
Phoenix, Arizona
480-717-7767  Cell

**Comment by ryanj** [comment]
Try the 2nd installation option: https://github.com/ryanj/origin-s2i-nodejs#installation

**Comment by tgaillard1** [comment]
That did the trick!  Thanks!
